#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: agora-glass_pumpkin
  description: agora-glass_pumpkin
  homepage: https://wiki.hyperledger.org/display/labs/Agora
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
